# Generated by Django 5.0.4 on 2025-02-05 14:19

from django.db import migrations

def create_unique_brands(apps, schema_editor):

    # декларираме моделите, които ще използваме
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    #деклрариме променлива с всички имена на марки
    unique_brands_names = shoe.objects.values_list('brand', flat=True).distinct()


                    # CREATE VS. BULK_CREATE
            # multiple requests vs. single request

    # вкарваме имената в новата таблица
    # процедурата прави заявка към базата за всеки запис поотделно
    # т.е. неоптимален вариант
    # INSERT INTO unique_brands(brand) VALUES (brand); COMMIT
    '''
    for brand in unique_brands_names:
        unique_brands.create(brand=brand)
    '''

    # същата процедура, но далеч по оптимизирано;
    # създават се записите и след това се прави една заявка с всички тях
    unique_brands.objects.bulk_create(
        [unique_brands(brand=brand) for brand in unique_brands_names])


def reverse_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrands')
    unique_brands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(create_unique_brands, reverse_unique_brands)
    ]
