# Generated by Django 5.0.4 on 2025-01-22 16:21

from django.db import migrations

def create_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    unique_brand_names = shoe.objects.values_list('brand', flat=True).distinct() # [Adidas, Nike, Puma]

# pgsql => INSERT INTO unique_brands(brand_name) VALUES (brand_name); COMMIT;

# First option for commiting data into DB:
#     for brand in unique_brand_names:
#         unique_brands.create(brand_name=brand)

# Second option for commiting data into DB:
    unique_brands.objects.bulk_create([unique_brands(brand=brand_name) for brand_name in unique_brand_names])


def reverse_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrands')
    unique_brands.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(create_unique_brands, reverse_unique_brands)
    ]
