# Generated by Django 5.0.4 on 2025-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(related_name='artists', to='main_app.song'),
        ),
    ]
