# Generated by Django 5.0.4 on 2025-03-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_driver_drivinglicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicense',
            name='license_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
