# Generated by Django 5.0.4 on 2025-03-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_owner_car_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main_app.owner'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
